# Generated by Django 5.1.1 on 2024-09-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reputation',
            field=models.IntegerField(default=0),
        ),
    ]
