# Generated by Django 5.1.1 on 2024-09-10 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_reputation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='reputation',
        ),
    ]
